vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - gruntfuggly.todo-tree
    - ikuyadeu.r
    - hbenl.vscode-test-explorer
    - streetsidesoftware.code-spell-checker-portuguese
    - streetsidesoftware.code-spell-checker-medical-terms
    - cschleiden.vscode-github-actions
    - editorconfig.editorconfig
    - donjayamanne.git-extension-pack
    - codezombiech.gitignore
    - james-yu.latex-workshop
    - richie5um2.vscode-sort-json
    - redhat.vscode-yaml
    - christian-kohler.path-intellisense
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    - alefragnani.bookmarks
    - ms-python.python
    - donjayamanne.githistory
    - eamodio.gitlens
    - ziyasal.vscode-open-in-github
    - https://www.dropbox.com/s/raw/2jlt5zlx70bj1yh/meakbiyik.vscode-r-test-adapter-0.4.1.vsix
    - https://www.dropbox.com/s/raw/2zrakl493ncy9ss/natqe.reload-0.0.6.vsix

image: franzbischoff/false.alarm:latest

tasks:
  - name: Setup
    init: cp -R /home/docker/* /home/gitpod && chown -R gitpod:gitpod /home/gitpod
